In [1]:
import time
import numpy as np 
import pandas as pd 

In [2]:
nd1 = np.random.random((100000, 100))

In [3]:
nd1

array([[0.65146868, 0.28979806, 0.30417884, ..., 0.09505554, 0.91595232,
        0.11172776],
       [0.43336245, 0.54080757, 0.92423282, ..., 0.83626226, 0.3290003 ,
        0.32485003],
       [0.48459791, 0.07298102, 0.94488436, ..., 0.84601229, 0.72391877,
        0.68018266],
       ...,
       [0.78182249, 0.8038249 , 0.73620398, ..., 0.53741735, 0.48879764,
        0.5519805 ],
       [0.19950606, 0.92854003, 0.18785094, ..., 0.32206911, 0.6549517 ,
        0.98530638],
       [0.05593437, 0.24955658, 0.37761425, ..., 0.00414391, 0.73478533,
        0.52859415]])

In [18]:
def npSpeed():
    time1 = time.time() 
    mean = nd1.mean() 
    time2 = time.time() 

    return mean, time2-time1

In [19]:
npSpeed()

(0.49999942979542894, 0.023938655853271484)

In [10]:
def pySpeed():
    time1 = time.time() 
    mean = sum(sum(nd1)) / nd1.size
    time2 = time.time()

    return mean, time2-time1

In [11]:
pySpeed()

(0.49999942979542855, 0.13620209693908691)

In [16]:
def loopSpeed():
    time1 = time.time() 
    sum = 0
    for i in range(nd1.shape[0]):
        for j in range(nd1.shape[1]):
            sum += nd1[i, j]
    
    time2 = time.time() 

    return sum/nd1.size, time2-time1 

In [17]:
loopSpeed()

(0.49999942979545686, 4.117252349853516)

Don't use loops

### Accessing NDArrays

In [20]:
nd2 = np.random.random((5,4))

In [21]:
nd2

array([[0.12723432, 0.57346802, 0.88756183, 0.02972074],
       [0.85026352, 0.64358011, 0.54252701, 0.83413369],
       [0.60543212, 0.12285025, 0.34837643, 0.70376191],
       [0.6978685 , 0.70555331, 0.05867709, 0.34570057],
       [0.54288773, 0.33018423, 0.06967607, 0.35305325]])

In [22]:
nd2[0, 1:3]

array([0.57346802, 0.88756183])

In [23]:
nd2[:, 0:3:2]

array([[0.12723432, 0.88756183],
       [0.85026352, 0.54252701],
       [0.60543212, 0.34837643],
       [0.6978685 , 0.05867709],
       [0.54288773, 0.06967607]])

In [25]:
# modifying
nd2[3] = [1,2,3,4]

In [26]:
nd2

array([[0.12723432, 0.57346802, 0.88756183, 0.02972074],
       [0.85026352, 0.64358011, 0.54252701, 0.83413369],
       [0.60543212, 0.12285025, 0.34837643, 0.70376191],
       [1.        , 2.        , 3.        , 4.        ],
       [0.54288773, 0.33018423, 0.06967607, 0.35305325]])

In [27]:
nd3 = np.random.random(5)

In [28]:
nd3

array([0.13443722, 0.02938149, 0.87947102, 0.97419273, 0.6989389 ])

In [29]:
idx = np.array([1,1,2,3])

In [30]:
nd3[idx]

array([0.02938149, 0.02938149, 0.87947102, 0.97419273])

In [32]:
# masking
nd2

array([[0.12723432, 0.57346802, 0.88756183, 0.02972074],
       [0.85026352, 0.64358011, 0.54252701, 0.83413369],
       [0.60543212, 0.12285025, 0.34837643, 0.70376191],
       [1.        , 2.        , 3.        , 4.        ],
       [0.54288773, 0.33018423, 0.06967607, 0.35305325]])

In [33]:
nd2.mean()

0.8782355609994118

In [34]:
nd2[nd2 < nd2.mean()]

array([0.12723432, 0.57346802, 0.02972074, 0.85026352, 0.64358011,
       0.54252701, 0.83413369, 0.60543212, 0.12285025, 0.34837643,
       0.70376191, 0.54288773, 0.33018423, 0.06967607, 0.35305325])

In [36]:
nd2[nd2 < nd2.mean()].shape, nd2.shape

((15,), (5, 4))

In [38]:
# element wise operations

nd4 = np.random.randint(0, 10, size=(2,4))

In [39]:
nd4

array([[5, 0, 7, 8],
       [8, 0, 9, 6]])

In [45]:
nd4 * 2.0

array([[10.,  0., 14., 16.],
       [16.,  0., 18., 12.]])

In [46]:
nd4 * 2

array([[10,  0, 14, 16],
       [16,  0, 18, 12]])

In [48]:
(nd4 * 2.0).dtype, (nd4 * 2).dtype

(dtype('float64'), dtype('int32'))

In [49]:
nd4 * nd4

array([[25,  0, 49, 64],
       [64,  0, 81, 36]])

In [51]:
nd4.dot(nd4.T)

array([[138, 151],
       [151, 181]])

In [58]:
nd4.astype(float) / (nd4+1)

array([[0.83333333, 0.        , 0.875     , 0.88888889],
       [0.88888889, 0.        , 0.9       , 0.85714286]])

In [59]:
nd4 / (nd4+1)

array([[0.83333333, 0.        , 0.875     , 0.88888889],
       [0.88888889, 0.        , 0.9       , 0.85714286]])